name: Cargo check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cargo_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
